//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvanceCaptura
    {
        public long IdACaptura { get; set; }
        public Nullable<int> CantidadRegistros { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public Nullable<decimal> PorcentajeTotal { get; set; }
    }
}
