//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvanceUbicacion
    {
        public long IdAUbicacion { get; set; }
        public Nullable<int> Ubicacion { get; set; }
        public string DescripcionUbicacion { get; set; }
        public string Motivo { get; set; }
    }
}
