//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestraProductos
    {
        public long IdMProducto { get; set; }
        public string Fecha { get; set; }
        public string Sku { get; set; }
        public string Locales { get; set; }
        public string TInventario { get; set; }
        public string Descripcion { get; set; }
        public string Marca { get; set; }
        public string UnidadMedida { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Moneda { get; set; }
        public string SubClase { get; set; }
        public string DescripcionSubClase { get; set; }
        public string Clase { get; set; }
        public string DescripcionClase { get; set; }
        public string SubDepartamento { get; set; }
        public string DescripcionSubDpto { get; set; }
        public string Departamento { get; set; }
        public string DescripcionDpto { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public string TipoCodBarra { get; set; }
        public string Ean { get; set; }
        public string Cantidad { get; set; }
    }
}
