//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUbicacion
    {
        public TipoUbicacion()
        {
            this.Ubicacion = new HashSet<Ubicacion>();
        }
    
        public long IdTUbicacion { get; set; }
        public string DescripcionUbicacion { get; set; }
    
        public virtual ICollection<Ubicacion> Ubicacion { get; set; }
    }
}
