//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.MCaptura_x_CDatos = new HashSet<MCaptura_x_CDatos>();
            this.TipoUsuario = new HashSet<TipoUsuario>();
        }
    
        public long IdUsuario { get; set; }
        public string Usuario1 { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual ICollection<MCaptura_x_CDatos> MCaptura_x_CDatos { get; set; }
        public virtual ICollection<TipoUsuario> TipoUsuario { get; set; }
    }
}
