//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvanceCaptura
    {
        public int IdAPatente { get; set; }
        public string Ubicacion { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> IdUbicacion { get; set; }
        public Nullable<int> IdTUbicacion { get; set; }
    
        public virtual TipoUbicacion TipoUbicacion { get; set; }
        public virtual Ubicacion Ubicacion1 { get; set; }
    }
}
