//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avance
    {
        public int IdAvance { get; set; }
        public Nullable<int> CantidadRegistro { get; set; }
        public string DescripcionPasillo { get; set; }
        public Nullable<decimal> MontoTipoUbicacion { get; set; }
        public string PorcentajeAvance { get; set; }
        public Nullable<int> Total { get; set; }
        public string TipoUbicacion { get; set; }
        public Nullable<int> IdLocal { get; set; }
    
        public virtual Locales Locales { get; set; }
    }
}
