//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kardex
    {
        public int idKardex { get; set; }
        public string sku { get; set; }
        public Nullable<System.DateTime> fechaKardex { get; set; }
        public Nullable<decimal> cantidadKardex { get; set; }
        public Nullable<int> idlocal { get; set; }
    
        public virtual Locales Locales { get; set; }
    }
}
