//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int idProductos { get; set; }
        public string descripcionProductos { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string moneda { get; set; }
        public string clase { get; set; }
        public string descripcionClase { get; set; }
        public string subClase { get; set; }
        public string descripcionSubClase { get; set; }
        public Nullable<bool> isEstado { get; set; }
        public Nullable<int> idEmpresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
