//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_TipoUsuario
    {
        public int idUser { get; set; }
        public int idTipoUsuario { get; set; }
        public Nullable<int> idEmpresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
