//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVANCE_INVENTARIO
    {
        public string PATENTE { get; set; }
        public Nullable<int> ID_TIPO_PAT { get; set; }
        public Nullable<int> ID_BODEGA { get; set; }
        public string MOTIVO { get; set; }
        public string TIPO_PATENTE { get; set; }
        public Nullable<int> ID_PATENTE { get; set; }
    
        public virtual ESTADO_PATENTE ESTADO_PATENTE { get; set; }
        public virtual TIPO_UBICACION TIPO_UBICACION { get; set; }
        public virtual UBICACION UBICACION { get; set; }
    }
}
