//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRA_PROCESO
    {
        public string NUMCONTEO { get; set; }
        public string FECHA { get; set; }
        public string CODIGO_INTERNO { get; set; }
        public string LOCALES { get; set; }
        public string TIPO_INVENTARIO { get; set; }
        public string DESCRIPCION { get; set; }
        public string MARCA { get; set; }
        public string UNIDAD_MEDIDA { get; set; }
        public string PRECIO { get; set; }
        public string MONEDA { get; set; }
        public string SUB_CLASE { get; set; }
        public string DESCRIPCION_SUBCLASE { get; set; }
        public string CLASE { get; set; }
        public string DESCRIPCION_CLASE { get; set; }
        public string SUB_DEPARTAMENTO { get; set; }
        public string DESCRIPCION_SUB_DPTO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string DESCRIPCION_DPTO { get; set; }
        public string FECHA_CREACION_ARCHIVO { get; set; }
        public string TIPO_CODBARRA { get; set; }
        public string EAN { get; set; }
        public string CANTIDAD { get; set; }
        public int IDMPROC { get; set; }
    }
}
