//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventarioEntities : DbContext
    {
        public InventarioEntities()
            : base("name=InventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AVANCE_INVENTARIO> AVANCE_INVENTARIO { get; set; }
        public virtual DbSet<ESTADO_MAESTRA> ESTADO_MAESTRA { get; set; }
        public virtual DbSet<ESTADO_PATENTE> ESTADO_PATENTE { get; set; }
        public virtual DbSet<ESTADO_USUARIO> ESTADO_USUARIO { get; set; }
        public virtual DbSet<MAESTRA_INPUT> MAESTRA_INPUT { get; set; }
        public virtual DbSet<MODIFICAR_CAPTURA> MODIFICAR_CAPTURA { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPO_UBICACION> TIPO_UBICACION { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<UBICACION> UBICACION { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<ESTADO_INVENTARIO> ESTADO_INVENTARIO { get; set; }
        public virtual DbSet<PORCENTAJE_AVANCE> PORCENTAJE_AVANCE { get; set; }
        public virtual DbSet<TIPO_BUSQUEDA> TIPO_BUSQUEDA { get; set; }
        public virtual DbSet<MAESTRA_CONGELADO> MAESTRA_CONGELADO { get; set; }
        public virtual DbSet<MAESTRA_PROCESO> MAESTRA_PROCESO { get; set; }
    }
}
