//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODIFICAR_CAPTURA
    {
        public int ID_MOD { get; set; }
        public string CONTEO1 { get; set; }
        public string CONTEO2 { get; set; }
        public Nullable<int> ID_EST { get; set; }
        public Nullable<int> ID_INPUT { get; set; }
    
        public virtual ESTADO_MAESTRA ESTADO_MAESTRA { get; set; }
        public virtual MAESTRA_INPUT MAESTRA_INPUT { get; set; }
    }
}
