//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORCENTAJE_AVANCE
    {
        public int ID_AVANCE { get; set; }
        public string REGISTROS { get; set; }
        public string EXTENDIDO { get; set; }
        public string PORCENTAJE { get; set; }
        public string TOTAL { get; set; }
        public string UBICACION { get; set; }
    }
}
