//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UBICACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UBICACION()
        {
            this.AVANCE_INVENTARIO = new HashSet<AVANCE_INVENTARIO>();
        }
    
        public int ID_PATENTE { get; set; }
        public Nullable<int> ID_PATENTE_BODEGA { get; set; }
        public string DESCRIPCION { get; set; }
        public string RANGO_BAJO { get; set; }
        public string RANGO_ALTO { get; set; }
        public string TOTAL { get; set; }
        public Nullable<int> ID_BODEGA { get; set; }
        public string AVANCE_CERRADO { get; set; }
        public string AVANCE_ABIERTO { get; set; }
        public string AVANCE_NULO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVANCE_INVENTARIO> AVANCE_INVENTARIO { get; set; }
        public virtual TIPO_UBICACION TIPO_UBICACION { get; set; }
    }
}
