//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Controlador.Reserva {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="reservaSoap", Namespace="localhost")]
    public partial class reserva : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReservaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public reserva() {
            this.Url = global::Controlador.Properties.Settings.Default.Controlador_reserva_reserva;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReservaCompletedEventHandler ReservaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("localhost/Reserva", RequestNamespace="localhost", ResponseNamespace="localhost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Reserva(
                    string codigo_dealer, 
                    string codigo_sucursal, 
                    string nombre_usuario, 
                    string num_nota_venta, 
                    string orden_compra, 
                    string modelo_vehiculo, 
                    string version_vehiculo, 
                    string color_vehiculo, 
                    string stock_asig, 
                    string nombre_cliente, 
                    string rut_cliente, 
                    string nom_vendedor, 
                    string rut_vendedor, 
                    string monto_reserva, 
                    string moneda, 
                    string mot_anula_vta, 
                    string fecha_reserva, 
                    string usuario, 
                    string password) {
            object[] results = this.Invoke("Reserva", new object[] {
                        codigo_dealer,
                        codigo_sucursal,
                        nombre_usuario,
                        num_nota_venta,
                        orden_compra,
                        modelo_vehiculo,
                        version_vehiculo,
                        color_vehiculo,
                        stock_asig,
                        nombre_cliente,
                        rut_cliente,
                        nom_vendedor,
                        rut_vendedor,
                        monto_reserva,
                        moneda,
                        mot_anula_vta,
                        fecha_reserva,
                        usuario,
                        password});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ReservaAsync(
                    string codigo_dealer, 
                    string codigo_sucursal, 
                    string nombre_usuario, 
                    string num_nota_venta, 
                    string orden_compra, 
                    string modelo_vehiculo, 
                    string version_vehiculo, 
                    string color_vehiculo, 
                    string stock_asig, 
                    string nombre_cliente, 
                    string rut_cliente, 
                    string nom_vendedor, 
                    string rut_vendedor, 
                    string monto_reserva, 
                    string moneda, 
                    string mot_anula_vta, 
                    string fecha_reserva, 
                    string usuario, 
                    string password) {
            this.ReservaAsync(codigo_dealer, codigo_sucursal, nombre_usuario, num_nota_venta, orden_compra, modelo_vehiculo, version_vehiculo, color_vehiculo, stock_asig, nombre_cliente, rut_cliente, nom_vendedor, rut_vendedor, monto_reserva, moneda, mot_anula_vta, fecha_reserva, usuario, password, null);
        }
        
        /// <remarks/>
        public void ReservaAsync(
                    string codigo_dealer, 
                    string codigo_sucursal, 
                    string nombre_usuario, 
                    string num_nota_venta, 
                    string orden_compra, 
                    string modelo_vehiculo, 
                    string version_vehiculo, 
                    string color_vehiculo, 
                    string stock_asig, 
                    string nombre_cliente, 
                    string rut_cliente, 
                    string nom_vendedor, 
                    string rut_vendedor, 
                    string monto_reserva, 
                    string moneda, 
                    string mot_anula_vta, 
                    string fecha_reserva, 
                    string usuario, 
                    string password, 
                    object userState) {
            if ((this.ReservaOperationCompleted == null)) {
                this.ReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReservaOperationCompleted);
            }
            this.InvokeAsync("Reserva", new object[] {
                        codigo_dealer,
                        codigo_sucursal,
                        nombre_usuario,
                        num_nota_venta,
                        orden_compra,
                        modelo_vehiculo,
                        version_vehiculo,
                        color_vehiculo,
                        stock_asig,
                        nombre_cliente,
                        rut_cliente,
                        nom_vendedor,
                        rut_vendedor,
                        monto_reserva,
                        moneda,
                        mot_anula_vta,
                        fecha_reserva,
                        usuario,
                        password}, this.ReservaOperationCompleted, userState);
        }
        
        private void OnReservaOperationCompleted(object arg) {
            if ((this.ReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReservaCompleted(this, new ReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ReservaCompletedEventHandler(object sender, ReservaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591