//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Captura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Captura()
        {
            this.Captura_Local_Producto = new HashSet<Captura_Local_Producto>();
            this.ModificacionCaptura = new HashSet<ModificacionCaptura>();
        }
    
        public int IdCaptura { get; set; }
        public string Sku { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<decimal> CantidadCaptura { get; set; }
        public string Lote { get; set; }
        public Nullable<System.DateTime> FechaLote { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<bool> IsEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Captura_Local_Producto> Captura_Local_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModificacionCaptura> ModificacionCaptura { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
