//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioPro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventarioNvoEntities : DbContext
    {
        public InventarioNvoEntities()
            : base("name=InventarioNvoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Captura> Captura { get; set; }
        public virtual DbSet<Comuna> Comuna { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Empresa_Giro> Empresa_Giro { get; set; }
        public virtual DbSet<Giro> Giro { get; set; }
        public virtual DbSet<Kardex> Kardex { get; set; }
        public virtual DbSet<Locales> Locales { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<TipoUbicacion> TipoUbicacion { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
        public virtual DbSet<User_TipoUsuario> User_TipoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
