//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioPro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InventarioProEntities : DbContext
    {
        public InventarioProEntities()
            : base("name=InventarioProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avance> Avance { get; set; }
        public virtual DbSet<AvanceCaptura> AvanceCaptura { get; set; }
        public virtual DbSet<Captura> Captura { get; set; }
        public virtual DbSet<Captura_Local_Producto> Captura_Local_Producto { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Kardex> Kardex { get; set; }
        public virtual DbSet<Locales> Locales { get; set; }
        public virtual DbSet<Locales_Ubicacion> Locales_Ubicacion { get; set; }
        public virtual DbSet<ModificacionCaptura> ModificacionCaptura { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<TipoUbicacion> TipoUbicacion { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<View_CantDiferenciaNegativa> View_CantDiferenciaNegativa { get; set; }
        public virtual DbSet<View_CantDiferenciaPositiva> View_CantDiferenciaPositiva { get; set; }
        public virtual DbSet<View_Locales> View_Locales { get; set; }
        public virtual DbSet<View_SkuCapturados> View_SkuCapturados { get; set; }
        public virtual DbSet<View_TipoUbicacion> View_TipoUbicacion { get; set; }
        public virtual DbSet<View_Ubicacion> View_Ubicacion { get; set; }
    
        public virtual ObjectResult<SP_ListadoDiferenciaNegativa_Result> SP_ListadoDiferenciaNegativa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ListadoDiferenciaNegativa_Result>("SP_ListadoDiferenciaNegativa");
        }
    
        public virtual ObjectResult<SP_ListadoDiferenciaPositiva_Result> SP_ListadoDiferenciaPositiva()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ListadoDiferenciaPositiva_Result>("SP_ListadoDiferenciaPositiva");
        }
    
        public virtual ObjectResult<SP_ListadoProductos_Result> SP_ListadoProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ListadoProductos_Result>("SP_ListadoProductos");
        }
    
        public virtual ObjectResult<SP_ListadoUbicaciones_Result> SP_ListadoUbicaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ListadoUbicaciones_Result>("SP_ListadoUbicaciones");
        }
    }
}
