//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModificacionCaptura
    {
        public int IdModificacion { get; set; }
        public Nullable<int> Conteo1 { get; set; }
        public Nullable<int> Conteo2 { get; set; }
        public Nullable<int> IdCaptura { get; set; }
    
        public virtual Captura Captura { get; set; }
    }
}
