//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public int idUbicacion { get; set; }
        public string descripcionUbicacion { get; set; }
        public Nullable<int> rangoBajo { get; set; }
        public Nullable<int> rangoAlto { get; set; }
        public string area { get; set; }
        public string dpto { get; set; }
        public string lineal { get; set; }
        public string metro { get; set; }
        public string pasillo { get; set; }
        public Nullable<int> idlocal { get; set; }
    
        public virtual Locales Locales { get; set; }
    }
}
