//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comuna
    {
        public Comuna()
        {
            this.Direccion = new HashSet<Direccion>();
        }
    
        public long IdComuna { get; set; }
        public string Comuna1 { get; set; }
        public Nullable<long> IdRegion { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<Direccion> Direccion { get; set; }
    }
}
