//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosPersonales
    {
        public DatosPersonales()
        {
            this.PreguntaSecreta = new HashSet<PreguntaSecreta>();
        }
    
        public long IdDPersonales { get; set; }
        public string Email { get; set; }
        public string RPreguntaSecreta { get; set; }
        public long IdUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<PreguntaSecreta> PreguntaSecreta { get; set; }
    }
}
