//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public long IdDireccion { get; set; }
        public string Direccion1 { get; set; }
        public string Numero { get; set; }
        public string Piso { get; set; }
        public string Dpto { get; set; }
        public Nullable<long> IdComuna { get; set; }
        public Nullable<long> IdSucursal { get; set; }
    
        public virtual Comuna Comuna { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
