//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.TipoCuenta = new HashSet<TipoCuenta>();
            this.Sucursal = new HashSet<Sucursal>();
        }
    
        public long IdEmpresa { get; set; }
        public string Nombre { get; set; }
        public string Rut { get; set; }
        public byte[] Dv { get; set; }
        public string Historia { get; set; }
        public string Nosotros { get; set; }
    
        public virtual ICollection<TipoCuenta> TipoCuenta { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
    }
}
