//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class pasaelda_PasaelDatoEntities : DbContext
    {
        public pasaelda_PasaelDatoEntities()
            : base("name=pasaelda_PasaelDatoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cargo> Cargo { get; set; }
        public DbSet<Comentario> Comentario { get; set; }
        public DbSet<Comuna> Comuna { get; set; }
        public DbSet<DatosPersonales> DatosPersonales { get; set; }
        public DbSet<Direccion> Direccion { get; set; }
        public DbSet<Email> Email { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<EstadoReserva> EstadoReserva { get; set; }
        public DbSet<MedioPago> MedioPago { get; set; }
        public DbSet<PathImagenhabitacion> PathImagenhabitacion { get; set; }
        public DbSet<PathImagenPortada> PathImagenPortada { get; set; }
        public DbSet<Precio> Precio { get; set; }
        public DbSet<PreguntaSecreta> PreguntaSecreta { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<Producto_x_TCondicion> Producto_x_TCondicion { get; set; }
        public DbSet<Puntaje> Puntaje { get; set; }
        public DbSet<Puntaje_x_Comentario> Puntaje_x_Comentario { get; set; }
        public DbSet<Region> Region { get; set; }
        public DbSet<Reserva> Reserva { get; set; }
        public DbSet<ServicioHabitacion> ServicioHabitacion { get; set; }
        public DbSet<ServicioSucursal> ServicioSucursal { get; set; }
        public DbSet<Sucursal> Sucursal { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Telefono> Telefono { get; set; }
        public DbSet<TerminoCondiciones> TerminoCondiciones { get; set; }
        public DbSet<THabitacion_x_SHabitacion> THabitacion_x_SHabitacion { get; set; }
        public DbSet<TipoCuenta> TipoCuenta { get; set; }
        public DbSet<TipoHabitacion> TipoHabitacion { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Usuario_x_Cargo_x_TCuenta> Usuario_x_Cargo_x_TCuenta { get; set; }
    
        public virtual int ActualizarPass(string usu, string pass)
        {
            var usuParameter = usu != null ?
                new ObjectParameter("usu", usu) :
                new ObjectParameter("usu", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarPass", usuParameter, passParameter);
        }
    
        public virtual int CrearUsuario(string usu, string pass)
        {
            var usuParameter = usu != null ?
                new ObjectParameter("usu", usu) :
                new ObjectParameter("usu", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearUsuario", usuParameter, passParameter);
        }
    
        public virtual ObjectResult<Detalle_x_SHabitacion_Result> Detalle_x_SHabitacion(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Detalle_x_SHabitacion_Result>("Detalle_x_SHabitacion", idProductoParameter);
        }
    
        public virtual ObjectResult<FPagoSucursal_Result> FPagoSucursal(Nullable<int> idSucursal)
        {
            var idSucursalParameter = idSucursal.HasValue ?
                new ObjectParameter("IdSucursal", idSucursal) :
                new ObjectParameter("IdSucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FPagoSucursal_Result>("FPagoSucursal", idSucursalParameter);
        }
    
        public virtual ObjectResult<Habitacion_x_Motel_Result> Habitacion_x_Motel(Nullable<int> idTHabitacion)
        {
            var idTHabitacionParameter = idTHabitacion.HasValue ?
                new ObjectParameter("IdTHabitacion", idTHabitacion) :
                new ObjectParameter("IdTHabitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Habitacion_x_Motel_Result>("Habitacion_x_Motel", idTHabitacionParameter);
        }
    
        public virtual ObjectResult<Habitacion_x_Motel_x_Detalle_Result> Habitacion_x_Motel_x_Detalle(Nullable<int> idsucursal)
        {
            var idsucursalParameter = idsucursal.HasValue ?
                new ObjectParameter("idsucursal", idsucursal) :
                new ObjectParameter("idsucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Habitacion_x_Motel_x_Detalle_Result>("Habitacion_x_Motel_x_Detalle", idsucursalParameter);
        }
    
        public virtual ObjectResult<HorarioHabitacion_Result> HorarioHabitacion(Nullable<int> idsucursal)
        {
            var idsucursalParameter = idsucursal.HasValue ?
                new ObjectParameter("idsucursal", idsucursal) :
                new ObjectParameter("idsucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HorarioHabitacion_Result>("HorarioHabitacion", idsucursalParameter);
        }
    
        public virtual ObjectResult<Imagen_x_Habitacion_Result> Imagen_x_Habitacion(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Imagen_x_Habitacion_Result>("Imagen_x_Habitacion", idProductoParameter);
        }
    
        public virtual ObjectResult<Listado_x_Motel_Result> Listado_x_Motel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Listado_x_Motel_Result>("Listado_x_Motel");
        }
    
        public virtual ObjectResult<ListadoMoteles_Result> ListadoMoteles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoMoteles_Result>("ListadoMoteles");
        }
    
        public virtual ObjectResult<MenuIndex_Result> MenuIndex()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MenuIndex_Result>("MenuIndex");
        }
    
        public virtual ObjectResult<Nullable<int>> Pagecounts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pagecounts");
        }
    
        public virtual ObjectResult<Portada_x_Carrusel_Result> Portada_x_Carrusel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Portada_x_Carrusel_Result>("Portada_x_Carrusel");
        }
    
        public virtual ObjectResult<Portada_x_Motel_Result> Portada_x_Motel(Nullable<int> idmotel)
        {
            var idmotelParameter = idmotel.HasValue ?
                new ObjectParameter("idmotel", idmotel) :
                new ObjectParameter("idmotel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Portada_x_Motel_Result>("Portada_x_Motel", idmotelParameter);
        }
    
        public virtual ObjectResult<Precio_x_Habitacion_Result> Precio_x_Habitacion(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Precio_x_Habitacion_Result>("Precio_x_Habitacion", idProductoParameter);
        }
    
        public virtual ObjectResult<Precio_x_Producto_Result> Precio_x_Producto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Precio_x_Producto_Result>("Precio_x_Producto");
        }
    
        public virtual ObjectResult<Precio_x_Producto_x_Max_Result> Precio_x_Producto_x_Max()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Precio_x_Producto_x_Max_Result>("Precio_x_Producto_x_Max");
        }
    
        public virtual ObjectResult<Precio_x_Producto_x_Min_Result> Precio_x_Producto_x_Min()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Precio_x_Producto_x_Min_Result>("Precio_x_Producto_x_Min");
        }
    
        public virtual ObjectResult<Servicio_x_Habitacion_Result> Servicio_x_Habitacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Servicio_x_Habitacion_Result>("Servicio_x_Habitacion");
        }
    
        public virtual ObjectResult<Servicio_x_Sucursal_Result> Servicio_x_Sucursal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Servicio_x_Sucursal_Result>("Servicio_x_Sucursal");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Sucursal_x_Telefonos_Result> Sucursal_x_Telefonos(Nullable<int> idsucursal)
        {
            var idsucursalParameter = idsucursal.HasValue ?
                new ObjectParameter("idsucursal", idsucursal) :
                new ObjectParameter("idsucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sucursal_x_Telefonos_Result>("Sucursal_x_Telefonos", idsucursalParameter);
        }
    
        public virtual int Detalle_Sucursal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Detalle_Sucursal");
        }
    
        public virtual int MenuIndex1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MenuIndex1");
        }
    
        public virtual int ValidarUsuario(string usuario, string clave)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ValidarUsuario", usuarioParameter, claveParameter);
        }
    }
}
