//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PathImagenhabitacion
    {
        public PathImagenhabitacion()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public long IdImagenH { get; set; }
        public string HabitacionPath { get; set; }
        public string ImagenBase64 { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
