//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio
    {
        public long IdPrecio { get; set; }
        public Nullable<int> Precio1 { get; set; }
        public Nullable<int> Precio2 { get; set; }
        public Nullable<int> Descuento { get; set; }
        public Nullable<long> IdProducto { get; set; }
        public string Horas { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
