//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.EstadoReserva = new HashSet<EstadoReserva>();
            this.Precio = new HashSet<Precio>();
            this.Producto_x_TCondicion = new HashSet<Producto_x_TCondicion>();
            this.THabitacion_x_SHabitacion = new HashSet<THabitacion_x_SHabitacion>();
            this.PathImagenhabitacion = new HashSet<PathImagenhabitacion>();
            this.Sucursal = new HashSet<Sucursal>();
        }
    
        public long IdProducto { get; set; }
        public string DescripcionProducto { get; set; }
        public string DetalleProducto { get; set; }
    
        public virtual ICollection<EstadoReserva> EstadoReserva { get; set; }
        public virtual ICollection<Precio> Precio { get; set; }
        public virtual ICollection<Producto_x_TCondicion> Producto_x_TCondicion { get; set; }
        public virtual ICollection<THabitacion_x_SHabitacion> THabitacion_x_SHabitacion { get; set; }
        public virtual ICollection<PathImagenhabitacion> PathImagenhabitacion { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
    }
}
