//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puntaje
    {
        public Puntaje()
        {
            this.Puntaje_x_Comentario = new HashSet<Puntaje_x_Comentario>();
        }
    
        public long IdPuntaje { get; set; }
        public string ItemPuntaje { get; set; }
        public long IdUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Puntaje_x_Comentario> Puntaje_x_Comentario { get; set; }
    }
}
