//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public long IdReserva { get; set; }
        public string FReserva { get; set; }
        public string HReserva { get; set; }
        public string NombreReserva { get; set; }
        public Nullable<long> IdEReserva { get; set; }
    
        public virtual EstadoReserva EstadoReserva { get; set; }
    }
}
