//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioHabitacion
    {
        public ServicioHabitacion()
        {
            this.THabitacion_x_SHabitacion = new HashSet<THabitacion_x_SHabitacion>();
        }
    
        public long IdSHabitacion { get; set; }
        public string DescripcionSHabitacion { get; set; }
        public string IhabitacionMediano { get; set; }
        public string IhabitacionPequeno { get; set; }
        public string DetalleServicio { get; set; }
    
        public virtual ICollection<THabitacion_x_SHabitacion> THabitacion_x_SHabitacion { get; set; }
    }
}
