//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public Sucursal()
        {
            this.Direccion = new HashSet<Direccion>();
            this.Empresa = new HashSet<Empresa>();
            this.MedioPago = new HashSet<MedioPago>();
            this.Email = new HashSet<Email>();
            this.PathImagenPortada = new HashSet<PathImagenPortada>();
            this.Producto = new HashSet<Producto>();
            this.ServicioSucursal = new HashSet<ServicioSucursal>();
            this.Telefono = new HashSet<Telefono>();
        }
    
        public long IdSucursal { get; set; }
        public string NombreSucursal { get; set; }
        public string DescripcionSucursal { get; set; }
        public string Nosotros { get; set; }
        public string Historia { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
        public string Contactanos { get; set; }
        public string Web { get; set; }
    
        public virtual ICollection<Direccion> Direccion { get; set; }
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual ICollection<MedioPago> MedioPago { get; set; }
        public virtual ICollection<Email> Email { get; set; }
        public virtual ICollection<PathImagenPortada> PathImagenPortada { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual ICollection<ServicioSucursal> ServicioSucursal { get; set; }
        public virtual ICollection<Telefono> Telefono { get; set; }
    }
}
