//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminoCondiciones
    {
        public TerminoCondiciones()
        {
            this.Producto_x_TCondicion = new HashSet<Producto_x_TCondicion>();
        }
    
        public long IdTCondicion { get; set; }
        public string FIni { get; set; }
        public string FTer { get; set; }
        public string RestriccionHorario { get; set; }
        public string DetalleRestriccion { get; set; }
        public string Hrs { get; set; }
        public string NoIncluye { get; set; }
        public string Observaciones { get; set; }
    
        public virtual ICollection<Producto_x_TCondicion> Producto_x_TCondicion { get; set; }
    }
}
