//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THabitacion_x_SHabitacion
    {
        public long IdSHabitacion { get; set; }
        public long IdTHabitacion { get; set; }
        public long IdProducto { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual ServicioHabitacion ServicioHabitacion { get; set; }
        public virtual TipoHabitacion TipoHabitacion { get; set; }
    }
}
