//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoHabitacion
    {
        public TipoHabitacion()
        {
            this.THabitacion_x_SHabitacion = new HashSet<THabitacion_x_SHabitacion>();
        }
    
        public long IdTHabitacion { get; set; }
        public string DescripcionTHabitacion { get; set; }
        public string LinkH { get; set; }
        public Nullable<int> TipoServicio { get; set; }
    
        public virtual ICollection<THabitacion_x_SHabitacion> THabitacion_x_SHabitacion { get; set; }
    }
}
