//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCuenta
    {
        public TipoCuenta()
        {
            this.Usuario_x_Cargo_x_TCuenta = new HashSet<Usuario_x_Cargo_x_TCuenta>();
        }
    
        public long IdTipoCuenta { get; set; }
        public string DescripcionCuenta { get; set; }
        public Nullable<long> IdEmpresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Usuario_x_Cargo_x_TCuenta> Usuario_x_Cargo_x_TCuenta { get; set; }
    }
}
