//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Controlador.Cotizacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CotizacionSoap", Namespace="localhost")]
    public partial class Cotizacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback cotizacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Cotizacion() {
            this.Url = global::Controlador.Properties.Settings.Default.Controlador_cotizacion_Cotizacion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event cotizacionCompletedEventHandler cotizacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("localhost/cotizacion", RequestNamespace="localhost", ResponseNamespace="localhost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] cotizacion(
                    string codigo_dealer, 
                    string codigo_sucursal, 
                    string num_cotiza, 
                    string nombre_usuario, 
                    string modelo_vehiculo, 
                    string version_vehiculo, 
                    string nombre_cliente, 
                    string rut_cliente, 
                    string tel_cliente, 
                    string mail_cliente, 
                    string monto, 
                    string moneda, 
                    string nom_vendedor, 
                    string rut_vendedor, 
                    string medio_showroom, 
                    string test_driver, 
                    string usuario, 
                    string password) {
            object[] results = this.Invoke("cotizacion", new object[] {
                        codigo_dealer,
                        codigo_sucursal,
                        num_cotiza,
                        nombre_usuario,
                        modelo_vehiculo,
                        version_vehiculo,
                        nombre_cliente,
                        rut_cliente,
                        tel_cliente,
                        mail_cliente,
                        monto,
                        moneda,
                        nom_vendedor,
                        rut_vendedor,
                        medio_showroom,
                        test_driver,
                        usuario,
                        password});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void cotizacionAsync(
                    string codigo_dealer, 
                    string codigo_sucursal, 
                    string num_cotiza, 
                    string nombre_usuario, 
                    string modelo_vehiculo, 
                    string version_vehiculo, 
                    string nombre_cliente, 
                    string rut_cliente, 
                    string tel_cliente, 
                    string mail_cliente, 
                    string monto, 
                    string moneda, 
                    string nom_vendedor, 
                    string rut_vendedor, 
                    string medio_showroom, 
                    string test_driver, 
                    string usuario, 
                    string password) {
            this.cotizacionAsync(codigo_dealer, codigo_sucursal, num_cotiza, nombre_usuario, modelo_vehiculo, version_vehiculo, nombre_cliente, rut_cliente, tel_cliente, mail_cliente, monto, moneda, nom_vendedor, rut_vendedor, medio_showroom, test_driver, usuario, password, null);
        }
        
        /// <remarks/>
        public void cotizacionAsync(
                    string codigo_dealer, 
                    string codigo_sucursal, 
                    string num_cotiza, 
                    string nombre_usuario, 
                    string modelo_vehiculo, 
                    string version_vehiculo, 
                    string nombre_cliente, 
                    string rut_cliente, 
                    string tel_cliente, 
                    string mail_cliente, 
                    string monto, 
                    string moneda, 
                    string nom_vendedor, 
                    string rut_vendedor, 
                    string medio_showroom, 
                    string test_driver, 
                    string usuario, 
                    string password, 
                    object userState) {
            if ((this.cotizacionOperationCompleted == null)) {
                this.cotizacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncotizacionOperationCompleted);
            }
            this.InvokeAsync("cotizacion", new object[] {
                        codigo_dealer,
                        codigo_sucursal,
                        num_cotiza,
                        nombre_usuario,
                        modelo_vehiculo,
                        version_vehiculo,
                        nombre_cliente,
                        rut_cliente,
                        tel_cliente,
                        mail_cliente,
                        monto,
                        moneda,
                        nom_vendedor,
                        rut_vendedor,
                        medio_showroom,
                        test_driver,
                        usuario,
                        password}, this.cotizacionOperationCompleted, userState);
        }
        
        private void OncotizacionOperationCompleted(object arg) {
            if ((this.cotizacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cotizacionCompleted(this, new cotizacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void cotizacionCompletedEventHandler(object sender, cotizacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cotizacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cotizacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591